import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';

// Optional: Demonstrate an async thunk using mock data from JSONPlaceholder
// createAsyncThunk generates promise lifecycle action types (pending, fulfilled, rejected)
export const fetchPosts = createAsyncThunk(
  'posts/fetchPosts',
  async (_, { rejectWithValue }) => {
    try {
      const response = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=3');
      if (!response.ok) {
        throw new Error('Failed to fetch posts');
      }
      const data = await response.json();
      // Map JSONPlaceholder structure to our state structure
      return data.map(post => ({
        id: post.id.toString(),
        title: post.title.substring(0, 30), // truncate for clean layout
        content: post.body,
        platform: 'Twitter/X' // Default platform for fetched posts
      }));
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

const initialState = {
  items: [
    { id: '1', title: 'First Post', content: 'This is my first post on this platform!', platform: 'LinkedIn' },
    { id: '2', title: 'Hello World', content: 'Learning Redux Toolkit in Full Stack Development lab.', platform: 'Instagram' }
  ],
  status: 'idle', // 'idle' | 'loading' | 'succeeded' | 'failed'
  error: null
};

const postsSlice = createSlice({
  name: 'posts',
  initialState,
  reducers: {
    // Action to add a new post
    addPost: (state, action) => {
      state.items.push(action.payload);
    },
    // Action to edit an existing post
    editPost: (state, action) => {
      const { id, title, content, platform } = action.payload;
      const existingPost = state.items.find(post => post.id === id);
      if (existingPost) {
        existingPost.title = title;
        existingPost.content = content;
        existingPost.platform = platform;
      }
    },
    // Action to delete a post
    deletePost: (state, action) => {
      const id = action.payload;
      state.items = state.items.filter(post => post.id !== id);
    }
  },
  // extraReducers allows the slice to respond to other action types, including async thunks
  extraReducers: (builder) => {
    builder
      .addCase(fetchPosts.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.status = 'succeeded';
        // Add fetched posts to the existing items (avoiding duplicates)
        action.payload.forEach(fetchedPost => {
          if (!state.items.some(item => item.id === fetchedPost.id)) {
            state.items.push(fetchedPost);
          }
        });
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.payload || action.error.message;
      });
  }
});

// Export actions generated by createSlice
export const { addPost, editPost, deletePost } = postsSlice.actions;

// Export the reducer to be registered in the store
export default postsSlice.reducer;
